private static void runTestCWE8() {
    /* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__while_true_01()).runTest("CWE835_Infinite_Loop__while_true_01");
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__for_01()).runTest("CWE835_Infinite_Loop__for_01");
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__for_empty_01()).runTest("CWE835_Infinite_Loop__for_empty_01");
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__do_true_01()).runTest("CWE835_Infinite_Loop__do_true_01");
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__while_01()).runTest("CWE835_Infinite_Loop__while_01");
            (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__do_01()).runTest("CWE835_Infinite_Loop__do_01");
            /* END-AUTOGENERATED-JAVA-TESTS-8 */
}