package ;

import testcasesupport.*;

public class Main {

    private static void runTestCWE2() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

                /* END-AUTOGENERATED-JAVA-TESTS-2 */
    }

    private static void runTestCWE3() {
        /* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

                /* END-AUTOGENERATED-JAVA-TESTS-3 */
    }
}