private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
    try {
        /* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

        /* END-AUTOGENERATED-SERVLET-TESTS-3 */
    } catch (Throwable t) {
        System.out.println(" Caught thowable from doGetCWE3 ");
        System.out.println(" Throwable's message = " + t.getMessage());
        System.out.println("Stack trace below");
        
        StackTraceElement stes[] = t.getStackTrace();
        
        for (StackTraceElement ste : stes) {
            System.out.println("  " + ste.toString());
        } 
    }
}