// Previous imports and package definitions...

public class CWE113_HTTP_Response_Splitting__Environment_addCookieServlet_01 extends AbstractTestCaseServlet
{
    // bad method unchanged...
    // goodG2B method unchanged...
    // goodB2G method unchanged...

    public void good(HttpServletRequest request, HttpServletResponse response) throws Throwable
    {
        goodG2B(request, response);
        goodB2G(request, response);
    }

    // Main method unchanged...
}