private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
    try {
        /* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

        /* END-AUTOGENERATED-SERVLET-TESTS-7 */
    } catch (Throwable t) {
        System.out.println(
                " Caught thowable from doGetCWE7 ");

        System.out.println(" Throwable's message = " + t.getMessage());

        System.out.println("Stack trace below");

        StackTraceElement stes[] = t.getStackTrace();

        for (StackTraceElement ste : stes) {
            System.out.println("  " + ste.toString());
        }
    }
}