package testcases.CWE835_Infinite_Loop;

import testcasesupport.*;

public class Main {

    public static void main(String[] args) {

        if (args.length != 0) {

            if (args[0].equals("-h") || args[0].equals("--help")) {

                System.err.println("To use this main, you can either run the program with no " +
                "command line arguments to run all test cases or you can specify one or more classes to test");
                System.err.println("For example:");
                System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
                System.exit(1);
            }

            for (String className : args) {

                try {

                    Class<?> myClass = Class.forName(className);

                    AbstractTestCase myObject = (AbstractTestCase) myClass.newInstance();

                    myObject.runTest(className);

                } catch (Exception ex) {

                    IO.writeLine("Could not run test for class " + className);
                    ex.printStackTrace();

                }

                IO.writeLine(""); // leave a blank line between classes

            }

        } else {

            // No command line args were used, we want to run every testcase

            runTestCWE1();
            runTestCWE2();
            runTestCWE3();
            runTestCWE4();
            runTestCWE5();
            runTestCWE6();
            runTestCWE7();
            runTestCWE8();
            runTestCWE9();
        }
    }

    private static void runTestCWE1() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE2() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE3() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE4() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE5() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE6() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE7() {
        // Placeholder for autogenerated tests
    }

    private static void runTestCWE8() {
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__while_true_01()).runTest("CWE835_Infinite_Loop__while_true_01");
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__for_01()).runTest("CWE835_Infinite_Loop__for_01");
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__for_empty_01()).runTest("CWE835_Infinite_Loop__for_empty_01");
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__do_true_01()).runTest("CWE835_Infinite_Loop__do_true_01");
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__while_01()).runTest("CWE835_Infinite_Loop__while_01");
        (new testcases.CWE835_Infinite_Loop.CWE835_Infinite_Loop__do_01()).runTest("CWE835_Infinite_Loop__do_01");
    }

    private static void runTestCWE9() {
        // Placeholder for autogenerated tests
    }
}