package testcases.CWE835_Infinite_Loop;

import testcasesupport.*;

public class Main {

private static void runTestCWE10() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-10 */

			/* END-AUTOGENERATED-JAVA-TESTS-10 */
}

}
