package testcases.CWE835_Infinite_Loop;

import testcasesupport.*;

public class Main {

package testcases.CWE835_Infinite_Loop;

import testcasesupport.*;

public class Main {

	public static void main(String[] args) {

private static void runTestCWE1() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
			/* END-AUTOGENERATED-JAVA-TESTS-1 */
}

}
