name: Java CI - CWE835-InfiniteLoopTestProject-final

on:
  push:
    paths:
      - 'CWE835-InfiniteLoopTestProject-final/**'
  pull_request:
    paths:
      - 'CWE835-InfiniteLoopTestProject-final/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean compile
        working-directory: CWE835-InfiniteLoopTestProject-final

      - name: Run tests
        run: mvn test
        working-directory: CWE835-InfiniteLoopTestProject-final
